<a href="https://colab.research.google.com/github/tu25003-7491-cyber/EU_M_Math-Repository/blob/main/Chap02_Ex_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import numpy.linalg as LA

A = np.array([[1, 2, 3],[1, 3, 2], [3, 1, 2]])
print(A)
print(LA.det(A))


[[1 2 3]
 [1 3 2]
 [3 1 2]]
-12.000000000000005
