<a href="https://colab.research.google.com/github/tu25003-7491-cyber/EU_M_Math-Repository/blob/main/Chap02_Ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import numpy.linalg as LA

A = np.array([[1, 2, 3],[1, 3, 2], [3, 1, 2]])
A_inv = LA.inv(A)
print("Aの逆行列:")
print(A_inv)

eigenvalues, eigenvectors = LA.eig(A)

print("固有値:")
print(eigenvalues)

print("固有ベクトル")
print(eigenvectors)

Aの逆行列:
[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値:
[ 6.         -1.41421356  1.41421356]
固有ベクトル
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]
