<a href="https://colab.research.google.com/github/tu25003-7491-cyber/EU_M_Math-Repository/blob/main/Chap05_Ex_01_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [ ]:
sample_array = np.arange(10)
print('sample_array', sample_array)

sample_array [0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [ ]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [ ]:
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [ ]:
sample_names =='a'

array([ True, False, False, False,  True])

In [ ]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [ ]:
cond_data = np.array([True, True, False, False, True])
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
print(np.where(cond_data, x_array, y_array))

[  1   2 300 400   5]


#練習問題5-1

In [ ]:
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

sample_names == 'b'
data[sample_names == 'b']

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

#練習問題5-2

In [ ]:
print(sample_names != 'c')
data_excluding_c = data[sample_names != 'c']
print(data_excluding_c)

[ True  True False  True  True]
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


#練習問題5-3

In [18]:
x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])
cond_data2 = np.array([False, False, True, True, False])
print(np.where(cond_data2, x_array, y_array))

[ 6  7  3  4 10]


In [19]:
cond_data = np.array([True, True, False, False, True])
print(cond_data)
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [22]:
sample_data = np.arange(10)
print('元のデータ', sample_data)
print('すべての要素の平方根', np.sqrt(sample_data))
print('すべての要素のネイピア指数関数', np.exp(sample_data))

元のデータ [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根 [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア指数関数 [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [25]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('最小値', sample_multi_array_datal.min())
print('最大値', sample_multi_array_datal.max())
print('平均値', sample_multi_array_datal.mean())
print('合計', sample_multi_array_datal.sum())

print('行の合計', sample_multi_array_datal.sum(axis=1))
print('列の合計', sample_multi_array_datal.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値 0
最大値 8
平均値 4.0
合計 36
行の合計 [ 3 12 21]
列の合計 [ 9 12 15]


In [26]:
cond_data = np.array([True, True, False, False, True])

print('Trueが少なくとも１つあるかどうか', cond_data.any())
print('すべてTrueかどうか', cond_data.all())

Trueが少なくとも１つあるかどうか True
すべてTrueかどうか False


In [27]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('対数差分', np.diag(sample_multi_array_datal))
print('対角成分の和', np.trace(sample_multi_array_datal))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対数差分 [0 4 8]
対角成分の和 12


#練習問題5-4


In [32]:
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2
print(np.sqrt(sample_multi_array_data2))

[[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


#練習問題5-5

In [34]:
print('最大値', sample_multi_array_data2.max())
print('最小値', sample_multi_array_data2.min())
print('合計', sample_multi_array_data2.sum())
print('平均値', sample_multi_array_data2.mean())

最大値 15
最小値 0
合計 120
平均値 7.5


#練習問題5-6

In [35]:
print('対角成分の和', np.trace(sample_multi_array_data2))

対角成分の和 30


In [43]:
sample_array = np.arange(10)
print(sample_array)

sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

sample_array2.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3, sample_array4], axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.vstack((sample_array3, sample_array4))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
np.concatenate([sample_array3,sample_array4], axis = 1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
np.hstack((sample_array3, sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [53]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array_vstack = np.vstack((sample_array3, sample_array4))
sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
first, second, third = np.split(sample_array_vstack, [1,3])
print('first\n',first)
print('second\n',second)
second[0]
print('third\n',third)

first
 [[1 2 3]]
second
 [[4 5 6]
 [7 8 9]]
third
 [[10 11 12]]


In [60]:
sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3, sample_array4, sample_array5))
print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [76]:
first, second, third, fourth =np.split(sample_array_vstack2, [2,3,5])
print('first\n',first)
print('second\n',second)
print('third\n',third)
print('fourth\n',fourth)

first
 [[1 2 3]
 [4 5 6]]
second
 [[7 8 9]]
third
 [[10 11 12]
 [13 14 15]]
fourth
 [[16 17 18]
 [19 20 21]]


In [77]:
first[0]

array([1, 2, 3])

In [78]:
first[1]

array([4, 5, 6])

In [79]:
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [80]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
sample_array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#練習問題5-7

In [85]:
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)
np.concatenate([sample_array1, sample_array2], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#練習問題5-8

In [86]:
np.concatenate([sample_array1, sample_array2], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

#練習問題5-9

In [87]:
sample_list = [1,2,3,4,5]
sample_array_from_list = np.array(sample_list)
result_broadcast = sample_array_from_list + 3
print(result_broadcast)

[4 5 6 7 8]
